spring:
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 384
        max-document-batch-size: 10000
    moonshot:
      api-key: sk-VZVf27hv8KwBr3Q2tPEUdHtcPZ8UyoKWoez892qEdKaIJ1j1
      chat:
        options:
          model: moonshot-v1-8k
          temperature: 0.7
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1
      embedding:
        enabled: true
        model: all-minilm
  datasource:
    url: jdbc:postgresql://localhost:5433/springai
    username: postgres
    password: qwe123
server:
  port: 9090
